### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rakeshdev90** [NVIDIA/cuopt#730]
**Describe the bug**
cuOpt fails with following validation error:
{
  "CUOPT_ERROR_TYPE": "ValidationError",
  "msg": "Number of pd requests should be inferior to 16384."
}
I am trying to solve large time-window VRP problems that require more than 16,384 pickup-delivery (PD) requests.
It prevents running the solver over longer planning horizons

**Steps/Code to reproduce bug**
Sample code to reproduce the error.

import numpy as np
import cudf
from cuopt import routing

def pd_limit_exceeded(n_pd_pairs=20000):
    n_locations = 10
    n_vehicles = 1
    cost = cudf.DataFrame(np.zeros((n_locations, n_locations)))
    n_orders = n_pd_pairs * 2  # pickup + delivery
    data_model = routing.DataModel(n_locations, n_vehicles, n_orders)
    data_model.add_cost_matrix(cost)
    order_locations = cudf.Series([1] * n_pd_pairs + [2] * n_pd_pairs)
    data_model.set_order_locations(order_locations)
    pickup_orders = cudf.Series(range(n_pd_pairs))
    delivery_orders = cudf.Series(range(n_pd_pairs, 2 * n_pd_pairs))
    data_model.set_pickup_delivery_pairs(pickup_orders, delivery_orders)
    solver_settings = routing.SolverSettings()
    solver_settings.set_time_limit(30)
    routing.Solve(data_model, solver_settings)

pd_limit_exceeded()

**Expected behavior**
Ability to solver larger problems with PD pair more than 16K.

**Environment details (please complete the following information):**
 Cuopt enviornment - 25.08

**Comment by rgsl888prabhu** [comment]
@Rakeshdev90 This issue should be resolved, can you please test it with 25.12 and let us know ?

**Comment by Rakeshdev90** [comment]
@rgsl888prabhu i tested the latest version (25.12), validation error is still there for PD pairs greater that 16384.
@adityasinghz Thanks for the additional information.
I want to know why there is a strict limit of 16,384. Does this relate to how GPU kernels are designed? If we could increase this limit, would we get results that can be trusted?

**Comment by adityasinghz** [comment]
I cannot run because just now my company's laptop got changed and I've windows now but as per design seems:

If we increase this limit, results would be trustworthy, but it requires redesigning the bit-packing scheme (currently 2 bits fragment + 14 bits block ID) and updating all GPU kernels that use this structure. The limit is a conservative encoding constraint, not a fundamental algorithmic limit `uint16_t` supports up to 65,535.
